volumes:
  qdrant_node1_data:
  qdrant_node2_data:

services:
  qdrant-node1:
    image: qdrant/qdrant:v1.13.4-metal
    platform: linux/arm64
    runtime: metal
    command: 
      - /qdrant/qdrant
      - --uri
      - http://qdrant-node1:6335
    volumes:
      - qdrant_node1_data:/qdrant/storage
    ports:
      - "6333:6333"  # Primary node HTTP
      - "6334:6334"  # Primary node gRPC
    networks:
      - qdrant-net
    environment:
      QDRANT__STORAGE__GPU_INDEXING: "true"
      QDRANT__CLUSTER__ENABLED: "true"
    deploy:
      resources:
        reservations:
          devices:
            - driver: metal
              count: 1

  qdrant-node2:
    image: qdrant/qdrant:v1.13.4-metal
    platform: linux/arm64
    runtime: metal
    command: 
      - /qdrant/qdrant
      - --bootstrap
      - http://qdrant-node1:6335
    volumes:
      - qdrant_node2_data:/qdrant/storage
    ports:
      - "6335:6333"  # Secondary node HTTP
      - "6336:6334"  # Secondary node gRPC
    networks:
      - qdrant-net
    environment:
      QDRANT__STORAGE__GPU_INDEXING: "true"
      QDRANT__CLUSTER__ENABLED: "true"
    deploy:
      resources:
        reservations:
          devices:
            - driver: metal
              count: 1

networks:
  qdrant-net:
    driver: bridge
